name: nerdik-staging

services:
  app:
    container_name: nerdik-staging-app
    networks:
      - nerdik
      - edge

  reverb:
    container_name: nerdik-staging-reverb
    networks:
      - nerdik
      - edge

  worker:
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512M

  scheduler:
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 256M

networks:
  edge:
    external: true
    name: nerdik-edge

volumes:
  storage:
    name: nerdik_staging_storage
    driver: local
  pgsql_data:
    name: nerdik_staging_pgsql_data
    driver: local
