name: nerdik-prod

volumes:
  storage:
    name: nerdik_storage
    driver: local
  pgsql_data:
    name: nerdik_pgsql_data
    driver: local
  caddy_data:
    name: nerdik_caddy_data
    driver: local
  caddy_config:
    name: nerdik_caddy_config
    driver: local
